openapi: "3.0.0"
info:
  title: "My API"
  version: "1.0.0"

paths:
  /hello:
    get:
      summary: "Obtiene un saludo"
      responses:
        '200':
          description: "Respuesta exitosa"
          content:
            application/json:
              example:
                message: "¡Hola desde la API!"
